language: node_js

node_js: 
    - 5.7.0

branches: 
    only: 
        - develop

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script: 
    - npm test


